// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/compilador/lexic/lexic.flex

/**
 * Assignatura 21780 - Compiladors
 * Estudis: Grau en InformÃ tica 
 * Itinerari: IntelÂ·ligÃ¨ncia Artificial i ComputaciÃ³
 *
 * Professor: Pere Palmer
 */
package compilador.lexic;

import java.io.*;
import java_cup.runtime.ComplexSymbolFactory.*;
import compilador.lexic.utils;
import java_cup.sym;
import compilador.main.MVP;


import compilador.sintactic.ParserSym;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\1\1\4"+
    "\1\5\4\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\6\21\2\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\0\6\30\24\31\1\32"+
    "\1\0\1\33\1\0\1\31\1\0\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\2\31\1\45"+
    "\1\46\1\47\1\50\1\51\1\31\1\52\1\53\1\54"+
    "\1\55\1\31\1\56\1\57\1\60\1\31\1\61\1\62"+
    "\1\63\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\2\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\17\23\1\26\1\2\1\27\1\30\1\0\1\31\1\0"+
    "\1\2\1\3\1\2\1\32\1\33\1\0\1\34\3\0"+
    "\1\35\1\36\1\37\11\23\1\40\5\23\1\41\7\23"+
    "\4\42\1\0\1\43\1\44\1\45\1\46\7\23\1\47"+
    "\1\23\1\50\1\23\1\51\1\52\1\53\12\23\1\54"+
    "\2\23\1\55\1\23\1\56\1\57\2\23\1\60\2\23"+
    "\1\61\3\23\1\62\3\23\1\63\1\23\1\64\1\65"+
    "\1\23\1\66\4\23\1\67\1\70\1\71\4\23\1\72"+
    "\1\73\1\74\1\75\1\23\1\76\1\23\1\77\1\23"+
    "\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\64"+
    "\0\64\0\64\0\u016c\0\64\0\u01a0\0\64\0\u01d4\0\u0208"+
    "\0\u023c\0\64\0\64\0\u0270\0\u02a4\0\u02d8\0\u030c\0\64"+
    "\0\64\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478"+
    "\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618"+
    "\0\64\0\u064c\0\64\0\64\0\u0104\0\64\0\u0680\0\u06b4"+
    "\0\u06e8\0\u071c\0\64\0\64\0\u0750\0\u0784\0\u07b8\0\u07ec"+
    "\0\u0820\0\64\0\64\0\64\0\u0854\0\u0888\0\u08bc\0\u08f0"+
    "\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u030c\0\u0a28\0\u0a5c"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\u030c\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8"+
    "\0\u0bfc\0\u0c30\0\u0c64\0\64\0\150\0\234\0\u064c\0\u0c98"+
    "\0\u07b8\0\u07ec\0\u0820\0\u030c\0\u0ccc\0\u0d00\0\u0d34\0\u0d68"+
    "\0\u0d9c\0\u0dd0\0\u0e04\0\u030c\0\u0e38\0\u030c\0\u0e6c\0\u030c"+
    "\0\u030c\0\u030c\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4"+
    "\0\u0fd8\0\u100c\0\u1040\0\u1074\0\64\0\u10a8\0\u10dc\0\u030c"+
    "\0\u1110\0\u030c\0\u030c\0\u1144\0\u1178\0\u030c\0\u11ac\0\u11e0"+
    "\0\u030c\0\u1214\0\u1248\0\u127c\0\u030c\0\u12b0\0\u12e4\0\u1318"+
    "\0\u030c\0\u134c\0\u030c\0\u030c\0\u1380\0\u13b4\0\u13e8\0\u141c"+
    "\0\u1450\0\u1484\0\u030c\0\u030c\0\u030c\0\u14b8\0\u14ec\0\u1520"+
    "\0\u1554\0\u030c\0\u030c\0\u030c\0\u030c\0\u1588\0\u030c\0\u15bc"+
    "\0\u030c\0\u15f0\0\u030c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\3\21"+
    "\1\22\1\23\1\24\1\25\1\26\2\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\27\1\35\1\36\2\27\1\37"+
    "\1\27\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\2\27\1\51\1\52\1\53\65\0\1\3"+
    "\4\0\1\3\53\0\1\3\3\0\2\4\2\0\1\4"+
    "\53\0\1\4\27\0\1\54\35\0\5\55\1\56\56\55"+
    "\1\57\1\60\2\61\2\57\1\52\53\57\1\62\1\57"+
    "\12\0\1\63\65\0\1\64\60\0\1\65\4\0\1\66"+
    "\102\0\1\67\12\0\1\70\6\0\1\71\23\0\4\21"+
    "\67\0\1\72\63\0\1\73\63\0\1\74\54\0\4\27"+
    "\5\0\2\27\2\0\25\27\22\0\4\27\5\0\2\27"+
    "\2\0\13\27\1\75\2\27\1\76\6\27\22\0\4\27"+
    "\5\0\2\27\2\0\14\27\1\77\10\27\22\0\4\27"+
    "\5\0\2\27\2\0\7\27\1\100\4\27\1\101\10\27"+
    "\22\0\4\27\5\0\2\27\2\0\11\27\1\102\13\27"+
    "\22\0\4\27\5\0\2\27\2\0\1\103\13\27\1\104"+
    "\4\27\1\105\3\27\22\0\4\27\5\0\2\27\2\0"+
    "\5\27\1\106\5\27\1\107\11\27\22\0\4\27\5\0"+
    "\2\27\2\0\1\110\13\27\1\111\10\27\22\0\4\27"+
    "\5\0\2\27\2\0\4\27\1\112\7\27\1\113\10\27"+
    "\22\0\4\27\5\0\2\27\2\0\16\27\1\114\6\27"+
    "\22\0\4\27\5\0\2\27\2\0\16\27\1\115\6\27"+
    "\22\0\4\27\5\0\2\27\2\0\4\27\1\116\20\27"+
    "\22\0\4\27\5\0\2\27\2\0\20\27\1\117\4\27"+
    "\22\0\4\27\5\0\2\27\2\0\16\27\1\120\2\27"+
    "\1\121\3\27\22\0\4\27\5\0\2\27\2\0\13\27"+
    "\1\122\11\27\22\0\4\27\5\0\2\27\2\0\7\27"+
    "\1\123\15\27\4\0\1\3\2\4\2\0\1\52\53\0"+
    "\1\52\7\0\1\124\56\0\1\3\4\0\1\125\53\0"+
    "\1\3\3\0\2\4\2\0\1\126\53\0\1\4\2\0"+
    "\1\3\2\4\2\0\1\127\53\0\1\52\1\0\11\65"+
    "\1\130\4\65\1\0\45\65\2\66\1\0\61\66\17\0"+
    "\2\131\62\0\3\132\61\0\4\133\5\0\1\133\3\0"+
    "\6\133\41\0\4\27\5\0\2\27\2\0\3\27\1\134"+
    "\21\27\22\0\4\27\5\0\2\27\2\0\16\27\1\135"+
    "\6\27\22\0\4\27\5\0\2\27\2\0\14\27\1\136"+
    "\10\27\22\0\4\27\5\0\2\27\2\0\1\137\24\27"+
    "\22\0\4\27\5\0\2\27\2\0\13\27\1\140\11\27"+
    "\22\0\4\27\5\0\2\27\2\0\10\27\1\141\6\27"+
    "\1\142\5\27\22\0\4\27\5\0\2\27\2\0\11\27"+
    "\1\143\13\27\22\0\4\27\5\0\2\27\2\0\16\27"+
    "\1\144\6\27\22\0\4\27\5\0\2\27\2\0\13\27"+
    "\1\145\11\27\22\0\4\27\5\0\2\27\2\0\20\27"+
    "\1\146\4\27\22\0\4\27\5\0\2\27\2\0\10\27"+
    "\1\147\14\27\22\0\4\27\5\0\2\27\2\0\3\27"+
    "\1\150\21\27\22\0\4\27\5\0\2\27\2\0\22\27"+
    "\1\151\2\27\22\0\4\27\5\0\2\27\2\0\20\27"+
    "\1\152\4\27\22\0\4\27\5\0\2\27\2\0\10\27"+
    "\1\153\3\27\1\154\10\27\22\0\4\27\5\0\2\27"+
    "\2\0\1\155\14\27\1\156\2\27\1\157\4\27\22\0"+
    "\4\27\5\0\2\27\2\0\16\27\1\160\6\27\22\0"+
    "\4\27\5\0\2\27\2\0\21\27\1\161\3\27\22\0"+
    "\4\27\5\0\2\27\2\0\15\27\1\162\7\27\22\0"+
    "\4\27\5\0\2\27\2\0\20\27\1\163\4\27\22\0"+
    "\4\27\5\0\2\27\2\0\10\27\1\164\14\27\21\0"+
    "\1\165\64\0\4\27\5\0\2\27\2\0\1\166\24\27"+
    "\22\0\4\27\5\0\2\27\2\0\11\27\1\167\13\27"+
    "\22\0\4\27\5\0\2\27\2\0\16\27\1\170\6\27"+
    "\22\0\4\27\5\0\2\27\2\0\17\27\1\171\5\27"+
    "\22\0\4\27\5\0\2\27\2\0\5\27\1\172\17\27"+
    "\22\0\4\27\5\0\2\27\2\0\4\27\1\173\20\27"+
    "\22\0\4\27\5\0\2\27\2\0\17\27\1\174\5\27"+
    "\22\0\4\27\5\0\2\27\2\0\2\27\1\175\22\27"+
    "\22\0\4\27\5\0\2\27\2\0\13\27\1\176\11\27"+
    "\22\0\4\27\5\0\2\27\2\0\13\27\1\177\11\27"+
    "\22\0\4\27\5\0\2\27\2\0\2\27\1\200\22\27"+
    "\22\0\4\27\5\0\2\27\2\0\3\27\1\201\21\27"+
    "\22\0\4\27\5\0\2\27\2\0\4\27\1\202\20\27"+
    "\22\0\4\27\5\0\2\27\2\0\21\27\1\203\3\27"+
    "\22\0\4\27\5\0\2\27\2\0\10\27\1\204\14\27"+
    "\22\0\4\27\5\0\2\27\2\0\4\27\1\205\20\27"+
    "\22\0\4\27\5\0\2\27\2\0\4\27\1\206\20\27"+
    "\22\0\4\27\5\0\2\27\2\0\10\27\1\207\14\27"+
    "\22\0\4\27\5\0\2\27\2\0\11\27\1\210\13\27"+
    "\22\0\4\27\5\0\2\27\2\0\24\27\1\211\22\0"+
    "\4\27\5\0\2\27\2\0\4\27\1\212\20\27\22\0"+
    "\4\27\5\0\2\27\2\0\20\27\1\213\4\27\22\0"+
    "\4\27\5\0\2\27\2\0\4\27\1\214\20\27\22\0"+
    "\4\27\5\0\2\27\2\0\20\27\1\215\4\27\22\0"+
    "\4\27\5\0\2\27\2\0\20\27\1\216\4\27\22\0"+
    "\4\27\5\0\2\27\2\0\4\27\1\217\20\27\22\0"+
    "\4\27\5\0\2\27\2\0\1\220\24\27\22\0\4\27"+
    "\5\0\2\27\2\0\16\27\1\221\6\27\22\0\4\27"+
    "\5\0\2\27\2\0\13\27\1\222\11\27\22\0\4\27"+
    "\5\0\2\27\2\0\11\27\1\223\13\27\22\0\4\27"+
    "\5\0\2\27\2\0\11\27\1\224\13\27\22\0\4\27"+
    "\5\0\2\27\2\0\4\27\1\225\20\27\22\0\4\27"+
    "\5\0\2\27\2\0\1\226\24\27\22\0\4\27\5\0"+
    "\2\27\2\0\10\27\1\227\14\27\22\0\4\27\5\0"+
    "\2\27\2\0\11\27\1\230\13\27\22\0\4\27\5\0"+
    "\2\27\2\0\3\27\1\231\21\27\22\0\4\27\5\0"+
    "\2\27\2\0\20\27\1\232\4\27\22\0\4\27\5\0"+
    "\2\27\2\0\13\27\1\233\11\27\22\0\4\27\5\0"+
    "\2\27\2\0\6\27\1\234\16\27\22\0\4\27\5\0"+
    "\2\27\2\0\13\27\1\235\11\27\22\0\4\27\5\0"+
    "\2\27\2\0\14\27\1\236\10\27\22\0\4\27\5\0"+
    "\2\27\2\0\13\27\1\237\11\27\22\0\4\27\5\0"+
    "\2\27\2\0\21\27\1\240\3\27\22\0\4\27\5\0"+
    "\2\27\2\0\13\27\1\241\11\27\22\0\4\27\5\0"+
    "\2\27\2\0\16\27\1\242\6\27\22\0\4\27\5\0"+
    "\2\27\2\0\4\27\1\243\20\27\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5668];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\3\11\1\1\1\11\1\1\1\11"+
    "\3\1\2\11\4\1\2\11\17\1\1\11\1\1\2\11"+
    "\1\0\1\11\1\0\3\1\2\11\1\0\1\1\3\0"+
    "\3\11\27\1\1\11\3\1\1\0\34\1\1\11\56\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    MVP mvp;

    public Scanner(java.io.Reader in, MVP mvp) {
    this.zzReader = in;
    this.mvp = mvp;
  }

    utils u = new utils();

    /***
       Mecanismes de gestiÃ³ de sÃ­mbols basat en ComplexSymbol. Tot i que en
       aquest cas potser no Ã©s del tot necessari.
     ***/
    /**
     ConstrucciÃ³ d'un symbol sense atribut associat.
     **/

    private ComplexSymbol symbol(int type) {
        Location l = new Location(yyline+1, yycolumn+1); // primera posiciÃ³ del token
        Location r = new Location(yyline+1, yycolumn+1+yylength()); // ultima posiciÃ³ del token
        ComplexSymbol val = new ComplexSymbol(ParserSym.terminalNames[type], type, l, r);
        return new ComplexSymbol(ParserSym.terminalNames[type], type, l, r, val);
    }


    /**
     ConstrucciÃ³ d'un symbol amb un atribut associat.
     **/


    private ComplexSymbol symbol(int type, Object value){
        Location l = new Location(yyline+1, yycolumn+1); // primera posiciÃ³ del token
        Location r = new Location(yyline+1, yycolumn+1+yylength()); // ultima posiciÃ³ del token
        return new ComplexSymbol(ParserSym.terminalNames[type], type, l, r, value);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return symbol(ParserSym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { mvp.setLexic("Símbol desconegut -> "+this.yytext()+", Levenshtein retorna ->" + u.Levenshtein(this.yytext()) + "\n"); return symbol(ParserSym.error);
            }
            // fall through
          case 65: break;
          case 2:
            { mvp.setLexic("White space '}' -> "+this.yytext()+"\n");
            }
            // fall through
          case 66: break;
          case 3:
            { mvp.setLexic("New line -> "+this.yytext()+"\n");
            }
            // fall through
          case 67: break;
          case 4:
            { mvp.setLexic("Símbol '(' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_lparen);
            }
            // fall through
          case 68: break;
          case 5:
            { mvp.setLexic("Símbol ')' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_rparen);
            }
            // fall through
          case 69: break;
          case 6:
            { mvp.setLexic("Símbol '*' -> "+this.yytext()+"\n"); return symbol(ParserSym.op_mul);
            }
            // fall through
          case 70: break;
          case 7:
            { mvp.setLexic("Símbol '+' -> "+this.yytext()+"\n"); return symbol(ParserSym.op_add);
            }
            // fall through
          case 71: break;
          case 8:
            { mvp.setLexic("Símbol ',' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_comma);
            }
            // fall through
          case 72: break;
          case 9:
            { mvp.setLexic("Símbol '-' -> "+this.yytext()+"\n"); return symbol(ParserSym.op_sub);
            }
            // fall through
          case 73: break;
          case 10:
            { mvp.setLexic("Símbol '.' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_dot);
            }
            // fall through
          case 74: break;
          case 11:
            { mvp.setLexic("Símbol '/' -> "+this.yytext()+"\n"); return symbol(ParserSym.op_div);
            }
            // fall through
          case 75: break;
          case 12:
            { mvp.setLexic("Literal 0 -> "+this.yytext()+"\n"); return symbol(ParserSym.l_int, new LiteralWrapper (0, this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 76: break;
          case 13:
            { mvp.setLexic("Literal integer -> "+this.yytext()+"\n"); return symbol(ParserSym.l_int, new LiteralWrapper (Integer.parseInt(this.yytext()), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 77: break;
          case 14:
            { mvp.setLexic("Símbol ':' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_colon);
            }
            // fall through
          case 78: break;
          case 15:
            { mvp.setLexic("Símbol ';' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_semicolon);
            }
            // fall through
          case 79: break;
          case 16:
            { mvp.setLexic("Símbol '<' -> "+this.yytext()+"\n"); return symbol(ParserSym.rel_lt);
            }
            // fall through
          case 80: break;
          case 17:
            { mvp.setLexic("Símbol '=' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_eq);
            }
            // fall through
          case 81: break;
          case 18:
            { mvp.setLexic("Símbol '>' -> "+this.yytext()+"\n"); return symbol(ParserSym.rel_gt);
            }
            // fall through
          case 82: break;
          case 19:
            { mvp.setLexic("Símbol 'ID' -> "+this.yytext()+"\n"); return symbol(ParserSym.identifier, new LiteralWrapper (this.yytext(), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 83: break;
          case 20:
            { mvp.setLexic("Símbol '[' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_lbracket);
            }
            // fall through
          case 84: break;
          case 21:
            { mvp.setLexic("Símbol ']' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_rbracket);
            }
            // fall through
          case 85: break;
          case 22:
            { mvp.setLexic("Símbol '{' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_lcbracket);
            }
            // fall through
          case 86: break;
          case 23:
            { mvp.setLexic("Símbol '}' -> "+this.yytext()+"\n"); return symbol(ParserSym.sym_rcbracket);
            }
            // fall through
          case 87: break;
          case 24:
            { mvp.setLexic("Símbol '!=' -> "+this.yytext()+"\n"); return symbol(ParserSym.rel_neq);
            }
            // fall through
          case 88: break;
          case 25:
            { mvp.setLexic("Literal string -> "+this.yytext()+"\n"); return symbol(ParserSym.l_string, new LiteralWrapper (this.yytext(), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 89: break;
          case 26:
            { mvp.setLexic("Símbol '++' -> "+this.yytext()+"\n"); return symbol(ParserSym.op_increment);
            }
            // fall through
          case 90: break;
          case 27:
            { mvp.setLexic("Símbol '--' -> "+this.yytext()+"\n"); return symbol(ParserSym.op_decrement);
            }
            // fall through
          case 91: break;
          case 28:
            { mvp.setLexic("Símbol '//' -> "+this.yytext()+"\n");
            }
            // fall through
          case 92: break;
          case 29:
            { mvp.setLexic("Símbol '<=' -> "+this.yytext()+"\n"); return symbol(ParserSym.rel_le);
            }
            // fall through
          case 93: break;
          case 30:
            { mvp.setLexic("Símbol '=' -> "+this.yytext()+"\n"); return symbol(ParserSym.rel_eq);
            }
            // fall through
          case 94: break;
          case 31:
            { mvp.setLexic("Símbol '>=' -> "+this.yytext()+"\n"); return symbol(ParserSym.rel_ge);
            }
            // fall through
          case 95: break;
          case 32:
            { mvp.setLexic("Símbol 'if' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_if);
            }
            // fall through
          case 96: break;
          case 33:
            { mvp.setLexic("Símbol 'or' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_or);
            }
            // fall through
          case 97: break;
          case 34:
            { mvp.setLexic("Literal character -> "+this.yytext()+"\n"); return symbol(ParserSym.l_char, new LiteralWrapper (this.yytext(), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 98: break;
          case 35:
            { mvp.setLexic("Literal binari -> "+this.yytext()+"\n"); return symbol(ParserSym.l_int, new LiteralWrapper (Integer.parseInt(this.yytext().substring(2, this.yytext().length()),2), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 99: break;
          case 36:
            { mvp.setLexic("Literal octal -> "+this.yytext()+"\n"); return symbol(ParserSym.l_int, new LiteralWrapper (Integer.parseInt(this.yytext().substring(2, this.yytext().length()),8), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 100: break;
          case 37:
            { mvp.setLexic("Literal hexadecimal -> "+this.yytext()+"\n"); return symbol(ParserSym.l_int, new LiteralWrapper (Integer.parseInt(this.yytext().substring(2, this.yytext().length()),16), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 101: break;
          case 38:
            { mvp.setLexic("Símbol 'and' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_and);
            }
            // fall through
          case 102: break;
          case 39:
            { mvp.setLexic("Símbol 'for' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_for);
            }
            // fall through
          case 103: break;
          case 40:
            { mvp.setLexic("Símbol 'int' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_int);
            }
            // fall through
          case 104: break;
          case 41:
            { mvp.setLexic("Símbol '%' -> "+this.yytext()+"\n"); return symbol(ParserSym.op_mod);
            }
            // fall through
          case 105: break;
          case 42:
            { mvp.setLexic("Símbol 'new' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_new);
            }
            // fall through
          case 106: break;
          case 43:
            { mvp.setLexic("Símbol 'not' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_not);
            }
            // fall through
          case 107: break;
          case 44:
            { mvp.setLexic("Símbol '/**/' -> "+this.yytext()+"\n");
            }
            // fall through
          case 108: break;
          case 45:
            { mvp.setLexic("Símbol 'char' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_char);
            }
            // fall through
          case 109: break;
          case 46:
            { mvp.setLexic("Símbol 'elif' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_elif);
            }
            // fall through
          case 110: break;
          case 47:
            { mvp.setLexic("Símbol 'else' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_else);
            }
            // fall through
          case 111: break;
          case 48:
            { mvp.setLexic("Símbol 'main(){}' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_main);
            }
            // fall through
          case 112: break;
          case 49:
            { mvp.setLexic("Símbol 'read()' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_read);
            }
            // fall through
          case 113: break;
          case 50:
            { mvp.setLexic("Símbol 'true' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_true, new LiteralWrapper(this.yytext(), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 114: break;
          case 51:
            { mvp.setLexic("Símbol 'array' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_array);
            }
            // fall through
          case 115: break;
          case 52:
            { mvp.setLexic("Símbol 'const' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_const);
            }
            // fall through
          case 116: break;
          case 53:
            { mvp.setLexic("Símbol 'false' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_false, new LiteralWrapper(this.yytext(), this.yyline+1, this.yycolumn+1));
            }
            // fall through
          case 117: break;
          case 54:
            { mvp.setLexic("Símbol 'print()' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_print);
            }
            // fall through
          case 118: break;
          case 55:
            { mvp.setLexic("Símbol 'tupel' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_tupel);
            }
            // fall through
          case 119: break;
          case 56:
            { mvp.setLexic("Símbol 'until' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_until);
            }
            // fall through
          case 120: break;
          case 57:
            { mvp.setLexic("Símbol 'while' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_while);
            }
            // fall through
          case 121: break;
          case 58:
            { mvp.setLexic("Símbol 'repeat' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_repeat);
            }
            // fall through
          case 122: break;
          case 59:
            { mvp.setLexic("Símbol 'return' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_return);
            }
            // fall through
          case 123: break;
          case 60:
            { mvp.setLexic("Símbol 'string' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_string);
            }
            // fall through
          case 124: break;
          case 61:
            { mvp.setLexic("Símbol 'bool' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_bool);
            }
            // fall through
          case 125: break;
          case 62:
            { mvp.setLexic("Símbol 'println()' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_println);
            }
            // fall through
          case 126: break;
          case 63:
            { mvp.setLexic("Símbol 'function(){}' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_function);
            }
            // fall through
          case 127: break;
          case 64:
            { mvp.setLexic("Símbol 'procedure(){}' -> "+this.yytext()+"\n"); return symbol(ParserSym.r_procedure);
            }
            // fall through
          case 128: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
